# Test Scenario 1, Test Case 3

def TestCase3():
    Browsers.Item[btChrome].Navigate("https://stephenlandaas.com/TuffyTypes/")
    Aliases.browser.BrowserWindow.Maximize()
    Aliases.browser.pageTuffytypes.selectTimer1.ClickItem("60 seconds")
    Aliases.browser.pageTuffytypes.Wait()
    aqObject.CheckProperty(Aliases.browser.pageTuffytypes.FindElement("#timer"), "contentText", cmpEqual, "Seconds Remaining: 60")
    Aliases.browser.pageTuffytypes.textnodeT.Click()
    Aliases.browser.pageTuffytypes.textnodeCsufTuffytypes.Keys("a")
    Aliases.browser.pageTuffytypes.buttonRestartbutton.ClickButton()
    Aliases.browser.pageTuffytypes.Wait()
    aqObject.CheckProperty(Aliases.browser.pageTuffytypes.FindElement("#timer"), "contentText", cmpEqual, "Seconds Remaining: 60")
    Aliases.browser.pageTuffytypes.selectTimer1.ClickItem("45 Seconds")
    Aliases.browser.pageTuffytypes.Wait()
    aqObject.CheckProperty(Aliases.browser.pageTuffytypes.FindElement("#timer"), "contentText", cmpEqual, "Seconds Remaining: 45")
    Aliases.browser.pageTuffytypes.textnodeGeneratedQuote.Click()
    Aliases.browser.pageTuffytypes.textnodeCsufTuffytypes.Keys("a")
    Aliases.browser.pageTuffytypes.buttonRestartbutton.ClickButton()
    Aliases.browser.pageTuffytypes.Wait()
    aqObject.CheckProperty(Aliases.browser.pageTuffytypes.FindElement("#timer"), "contentText", cmpEqual, "Seconds Remaining: 45")
    Aliases.browser.pageTuffytypes.selectTimer1.ClickItem("30 Seconds")
    Aliases.browser.pageTuffytypes.Wait()
    aqObject.CheckProperty(Aliases.browser.pageTuffytypes.FindElement("#timer"), "contentText", cmpEqual, "Seconds Remaining: 30")
    Aliases.browser.pageTuffytypes.textnodeGeneratedQuote.Click()
    Aliases.browser.pageTuffytypes.textnodeCsufTuffytypes.Keys("a")
    Aliases.browser.pageTuffytypes.buttonRestartbutton.ClickButton()
    Aliases.browser.pageTuffytypes.Wait()
    aqObject.CheckProperty(Aliases.browser.pageTuffytypes.FindElement("#timer"), "contentText", cmpEqual, "Seconds Remaining: 30")
    Aliases.browser.pageTuffytypes.selectTimer1.ClickItem("15 seconds")
    Aliases.browser.pageTuffytypes.Wait()
    aqObject.CheckProperty(Aliases.browser.pageTuffytypes.FindElement("#timer"), "contentText", cmpEqual, "Seconds Remaining: 15")
    Aliases.browser.pageTuffytypes.textnodeGeneratedQuote.Click()
    Aliases.browser.pageTuffytypes.textnodeCsufTuffytypes.Keys("a")
    Aliases.browser.pageTuffytypes.buttonRestartbutton.ClickButton()
    aqObject.CheckProperty(Aliases.browser.pageTuffytypes.FindElement("#timer"), "contentText", cmpEqual, "Seconds Remaining: 15")
